syntax enable
set number
set runtimepath+=~/.vim_runtime
set ts=4
set autoindent
set expandtab
set shiftwidth=4
set showmatch

source ~/.vim_runtime/vimrcs/basic.vim
source ~/.vim_runtime/vimrcs/filetypes.vim
source ~/.vim_runtime/vimrcs/plugins_config.vim
source ~/.vim_runtime/vimrcs/extended.vim

try
source ~/.vim_runtime/my_configs.vim
catch
endtry

